### ISSUE TITLE
Add config file support

### ISSUE THREAD

**Issue by goldenstein64** [goldenstein64/llynx#1]
Adding support for reading from a `.llynxrc` file or `.editorconfig` file would help with CLI ergonomics.

A default file could look like this:

```toml
settings = ".vscode/settings.json"
tree = ".lls_addons"
server = "https://luarocks.org/m/lls-addons"
```
